language: node_js
node_js:
- "10.9.0"
script:
- npm run build
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy; fi
cache:
  directories:
  - node_modules
env:
  global:
    - GIT_NAME: SankomDesign
    - GIT_EMAIL: sankomdesign/sankomdesign 
    - GITHUB_REPO: sankomdesign/sankomdesign 
    - GIT_SOURCE: _docpress